---
- name: config | Configuring Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_file }}"
    owner: "{{ prometheus_user_info['user'] }}"
    group: "{{ prometheus_user_info['group'] }}"
    mode: u=rw,g=r,o=r
  notify:
    - restart prometheus
  become: true

- name: config | Ensuring {{ prometheus_local_storage }} Exists
  ansible.builtin.file:
    path: "{{ prometheus_local_storage }}"
    state: directory
    owner: "{{ prometheus_user_info['user'] }}"
    group: "{{ prometheus_user_info['group'] }}"
    mode: u=rw,g=r,o=r
  become: true
