---
# tasks file for ansible-prometheus
- name: Lookup vars based on architecture
  ansible.builtin.include_vars: "{{ ansible_architecture }}.yml"

- name: Manage Prometheus user(s)
  ansible.builtin.include_tasks: user.yml

- name: Install Prometheus
  ansible.builtin.include_tasks: install.yml

- name: Configure Prometheus
  ansible.builtin.include_tasks: config.yml

- name: Manage Prometheus service
  ansible.builtin.include_tasks: service.yml
