---
- name: service | Configuring Prometheus Service
  ansible.builtin.template:
    src: etc/systemd/system/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: u=rw,g=r,o=r
  notify:
    - reload systemd
    - restart prometheus
  become: true
  when: ansible_service_mgr == "systemd"

- name: service | Ensuring Prometheus Service Is Started and Enabled
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: true
  become: true
