---
# handlers file for ansible-prometheus
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
  become: true

- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted
  become: true
